### ISSUE TITLE
Remove iOS Conf Budapest?

### ISSUE THREAD

**Issue by vincent-pradeilles** [Lascorbe/CocoaConferences#170]
Since the organisers announced that event was cancelled ([https://twitter.com/iosconfbudapest/status/1100673454922186752](https://twitter.com/iosconfbudapest/status/1100673454922186752)), should it be removed from the listing?

**Comment by cgrail** [comment]
I've also removed it from our list: https://github.com/tech-conferences/conference-data/pull/803

**Comment by mariusc** [comment]
Yeah, we should remove it. Do you want to open a MR 😅? Or should I?

**Comment by vincent-pradeilles** [comment]
I don't have the time to do it right now, feel free to if you want :)

**Comment by mariusc** [comment]
Done. Thanks for the heads-up :)
