### ISSUE TITLE
May I add Swift server-side only conference ?

### ISSUE THREAD

**Issue by emarashliev** [Lascorbe/CocoaConferences#188]

**Comment by Lascorbe** [comment]
Hmm good question, I think it could be relevant, but feels like it doesn't fit on the current setup of the lists.

Maybe we can add a new section? WDYT @davedelong @mariusc ?

**Comment by emarashliev** [comment]
Yeah, I felt the same way, that's why opened this issue 😀

**Comment by fassko** [comment]
I think it should be added but as @Lascorbe mentioned different list. I watched last year's talks and it was highly relevant for other Swift developments.

**Comment by davedelong** [comment]
I'm fine with it. It'd be simpler to make them part of the "cocoa" list, but I don't mind if we want to break it out in to a third list.

**Comment by emarashliev** [comment]
Thank you so much guys! 🙏 I opened a Pull Request #191 . I'll close the issue as well.
