### ISSUE TITLE
Github Pages deployments are not happening

### ISSUE THREAD

**Issue by davedelong** [Lascorbe/CocoaConferences#330]
https://github.com/Lascorbe/CocoaConferences/deployments

Recent PRs have not been triggering new site builds.

**Comment by davedelong** [comment]
I've been applying all the security/dependabot updates I can identify, in case GitHub is blocking the deployments because of outstanding issues.

So far it hasn't seemed to have done anything.

**Comment by Lascorbe** [comment]
thanks for reporting @davedelong! fixed :)
