### ISSUE TITLE
Create a more readable web page using gh-pages

### ISSUE THREAD

**Issue by Abizern** [Lascorbe/CocoaConferences#79]
Have a look at my fork and branch https://github.com/Abizern/CocoaConferences/tree/gh-pages

(No pull request as you don't have a gh-pages branch)

Simply by using the automatic page generator and picking the first theme, and using the readme.markdown file you can see a nice web page at http://abizern.org/CocoaConferences/

If you do the same thing in your repo you can have the same page at https://Lascorbe.github.io/CocoaConferences/ and choose whatever theme you like. Since you've moved to tables, this looks quite nice.

**Comment by Lascorbe** [comment]
Oh yeah, that looks way better! Thanks @Abizern!!! 🍷

**Comment by Lascorbe** [comment]
Done! 🍻  http://lascorbe.github.io/CocoaConferences/
